// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyBanHangDoAnThucUong.Data;

#nullable disable

namespace QuanLyBanHangDoAnThucUong.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260601014311_NhanCapHeThong_Phan1_UpdateDatabase")]
    partial class NhanCapHeThong_Phan1_UpdateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.BienTheMonAn", b =>
                {
                    b.Property<int>("MaBienThe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBienThe"), 1L, 1);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaBan")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("HinhAnhMonAn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaMonAn")
                        .HasColumnType("int");

                    b.Property<string>("MoTaMonAn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MonAnMuaThem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongMon")
                        .HasColumnType("int");

                    b.Property<string>("TrangThaiMonAn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBienThe");

                    b.HasIndex("MaMonAn");

                    b.ToTable("BienTheMonAn", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaCTDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTDonHang"), 1L, 1);

                    b.Property<decimal>("GiaBan")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MaBienThe")
                        .HasColumnType("int");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongMua")
                        .HasColumnType("int");

                    b.HasKey("MaCTDonHang");

                    b.HasIndex("MaBienThe");

                    b.HasIndex("MaDonHang");

                    b.ToTable("CT_DonHang", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.ChuongTrinhKhuyenMai", b =>
                {
                    b.Property<int>("MaKMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKMai"), 1L, 1);

                    b.Property<DateTime>("NgayBDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungKMai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PhanTramGiam")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TenChTrinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiKMai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKMai");

                    b.ToTable("ChuongTrinhKhuyenMai", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.CT_GioHang", b =>
                {
                    b.Property<int>("MaCTGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTGioHang"), 1L, 1);

                    b.Property<decimal>("GiaBan")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MaBienThe")
                        .HasColumnType("int");

                    b.Property<int>("MaGioHang")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("UocTinhThanhTien")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("MaCTGioHang");

                    b.HasIndex("MaBienThe");

                    b.HasIndex("MaGioHang");

                    b.ToTable("CT_GioHang", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.DanhGiaMonAn", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"), 1L, 1);

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaKH")
                        .HasColumnType("int");

                    b.Property<int?>("MaMonAn")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayPhanHoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhanHoiCuaDoiTac")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThaiHienThi")
                        .HasColumnType("bit");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaMonAn");

                    b.ToTable("DanhGiaMonAn", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.DieuLe", b =>
                {
                    b.Property<int>("MaDieuLe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDieuLe"), 1L, 1);

                    b.Property<string>("ChiTietDieuLe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThemDieuLe")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhiChietKhau")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TenDieuLe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaDieuLe");

                    b.ToTable("DieuLe", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.DoiTac", b =>
                {
                    b.Property<int>("MaDoiTac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDoiTac"), 1L, 1);

                    b.Property<string>("DiaChiDoiTac")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmailDTac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("SoDTDoiTac")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TenQuanDoiTac")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiDoiTac")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDoiTac");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("DoiTac", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"), 1L, 1);

                    b.Property<decimal>("GiamGia")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("LyDoHuy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaGianHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaKH")
                        .HasColumnType("int");

                    b.Property<int?>("MaKMai")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTaoDon")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhiDichVuSan")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PhiShip")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ThanhTienKhachTra")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ThanhTienQuanNhan")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TongTienMon")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TrangThaiDonHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDonHang");

                    b.HasIndex("MaGianHang");

                    b.HasIndex("MaKH");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.GianHang", b =>
                {
                    b.Property<int>("MaGianHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGianHang"), 1L, 1);

                    b.Property<string>("DanhGiaGianHang")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DanhGiaGianHang");

                    b.Property<string>("DiaChiCuThe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeSpan>("GioDong")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioMo")
                        .HasColumnType("time");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LuotXem")
                        .HasColumnType("int");

                    b.Property<int>("MaDieuLe")
                        .HasColumnType("int");

                    b.Property<int>("MaDoiTac")
                        .HasColumnType("int");

                    b.Property<string>("PhuongXa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenGianHang")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ThanhPho")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiGianHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaGianHang");

                    b.HasIndex("MaDieuLe");

                    b.HasIndex("MaDoiTac");

                    b.ToTable("GianHang", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"), 1L, 1);

                    b.Property<int?>("MaKH")
                        .HasColumnType("int");

                    b.HasKey("MaGioHang");

                    b.HasIndex("MaKH");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"), 1L, 1);

                    b.Property<string>("DiaChiCuThe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("EmailKH")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinhKH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HangThanhVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongXa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDTKH")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TenKH")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThanhPho")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKH");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.KhuyenMai", b =>
                {
                    b.Property<int>("MaKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuyenMai"), 1L, 1);

                    b.Property<decimal>("DieuKienApDung")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MaGiamGia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaGianHang")
                        .HasColumnType("int");

                    b.Property<int>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<bool>("SuDung1Lan")
                        .HasColumnType("bit");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Kích hoạt");

                    b.HasKey("MaKhuyenMai");

                    b.HasIndex("MaGiamGia")
                        .IsUnique();

                    b.HasIndex("MaGianHang");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.LichSuTimKiem", b =>
                {
                    b.Property<int>("MaLSTimKiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLSTimKiem"), 1L, 1);

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTimKiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TuKhoa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaLSTimKiem");

                    b.HasIndex("MaKH");

                    b.ToTable("LichSuTimKiem", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.MonAn", b =>
                {
                    b.Property<int>("MaMonAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMonAn"), 1L, 1);

                    b.Property<int>("MaGianHang")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiMon")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuotBan")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuotDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("SoSaoTrungBinh")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ThanhPhan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaMonAn");

                    b.HasIndex("MaGianHang");

                    b.HasIndex("MaLoaiMon");

                    b.ToTable("MonAn", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"), 1L, 1);

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.TheLoaiMonAn", b =>
                {
                    b.Property<int>("MaLoaiMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiMon"), 1L, 1);

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoaiMon");

                    b.ToTable("TheLoaiMonAn", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"), 1L, 1);

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.BienTheMonAn", b =>
                {
                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.MonAn", "MonAn")
                        .WithMany("BienTheMonAns")
                        .HasForeignKey("MaMonAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.ChiTietDonHang", b =>
                {
                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.BienTheMonAn", "BienTheMonAn")
                        .WithMany()
                        .HasForeignKey("MaBienThe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienTheMonAn");

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.CT_GioHang", b =>
                {
                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.BienTheMonAn", "BienTheMonAn")
                        .WithMany()
                        .HasForeignKey("MaBienThe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.GioHang", "GioHang")
                        .WithMany("CT_GioHangs")
                        .HasForeignKey("MaGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienTheMonAn");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.DanhGiaMonAn", b =>
                {
                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.MonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("MaMonAn")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DonHang");

                    b.Navigation("KhachHang");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.DoiTac", b =>
                {
                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("DoiTac")
                        .HasForeignKey("QuanLyBanHangDoAnThucUong.Models.Entities.DoiTac", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.DonHang", b =>
                {
                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.GianHang", "GianHang")
                        .WithMany()
                        .HasForeignKey("MaGianHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GianHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.GianHang", b =>
                {
                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.DieuLe", "DieuLe")
                        .WithMany("GianHangs")
                        .HasForeignKey("MaDieuLe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.DoiTac", "DoiTac")
                        .WithMany("GianHangs")
                        .HasForeignKey("MaDoiTac")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DieuLe");

                    b.Navigation("DoiTac");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.GioHang", b =>
                {
                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.KhachHang", b =>
                {
                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("QuanLyBanHangDoAnThucUong.Models.Entities.KhachHang", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.KhuyenMai", b =>
                {
                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.GianHang", "GianHang")
                        .WithMany()
                        .HasForeignKey("MaGianHang");

                    b.Navigation("GianHang");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.LichSuTimKiem", b =>
                {
                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.MonAn", b =>
                {
                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.GianHang", "GianHang")
                        .WithMany("MonAns")
                        .HasForeignKey("MaGianHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.TheLoaiMonAn", "TheLoaiMonAn")
                        .WithMany("MonAns")
                        .HasForeignKey("MaLoaiMon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GianHang");

                    b.Navigation("TheLoaiMonAn");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyBanHangDoAnThucUong.Models.Entities.VaiTro", "VaiTro")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.DieuLe", b =>
                {
                    b.Navigation("GianHangs");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.DoiTac", b =>
                {
                    b.Navigation("GianHangs");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.GianHang", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.GioHang", b =>
                {
                    b.Navigation("CT_GioHangs");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.MonAn", b =>
                {
                    b.Navigation("BienTheMonAns");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.TaiKhoan", b =>
                {
                    b.Navigation("DoiTac");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.TheLoaiMonAn", b =>
                {
                    b.Navigation("MonAns");
                });

            modelBuilder.Entity("QuanLyBanHangDoAnThucUong.Models.Entities.VaiTro", b =>
                {
                    b.Navigation("TaiKhoans");
                });
#pragma warning restore 612, 618
        }
    }
}
